# Un playbook pour la mise à jour des eléments critiques

- hosts: all
  tasks:
    - name: Update openssh
      apt: 
         name: openssh-server
         state: latest
         update_cache: yes

- hosts: app
  tasks:
    - name: Update Apache
      apt:
         name: apache2
         state: latest
         update_cache: yes

- hosts: db
  tasks: 
    - name: Update Mariadb
      apt:
         name: mariadb-server
         state: latest
         update_cache: yes

    
          
